# Generated by Django 4.1.7 on 2023-04-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateuser',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidateuser',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidateuser',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='candidateuser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photo'),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photo'),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidateuser',
            name='candidate_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='company_address',
            field=models.TextField(null=True),
        ),
    ]
