# Generated by Django 4.1.7 on 2023-04-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_candidateuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateuser',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
