# Generated by Django 4.1.7 on 2023-04-09 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_jobadd_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobadd',
            name='job_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobadd',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
