# Generated by Django 4.1.7 on 2023-04-11 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_jobadd_job_title_alter_jobadd_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(null=True, upload_to='resume')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobadd')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.candidateuser')),
            ],
        ),
    ]
