# Generated by Django 4.1.7 on 2023-04-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
