# Generated by Django 4.1.7 on 2023-04-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_application_selected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobadd',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
