# Generated by Django 4.1.7 on 2023-04-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_application_username_jobadd_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobadd',
            name='skills_required',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
