# Generated by Django 4.1.7 on 2023-05-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='registration_status',
            field=models.CharField(choices=[('Pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=100),
        ),
    ]
