# Generated by Django 4.1.7 on 2023-05-18 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_jobadd_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobadd',
            name='is_active',
        ),
    ]
