# Generated by Django 4.1.7 on 2023-05-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_jobadd_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateuser',
            name='status',
            field=models.CharField(choices=[('under_processing', 'Under Processing'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='under_processing', max_length=20),
        ),
    ]
