# Generated by Django 4.1.5 on 2023-06-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_candidateuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateuser',
            name='skills',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='job_selection',
            field=models.CharField(choices=[('Selected ', ' Selected'), ('Pending', 'Pending'), ('Not_Selected', 'Not_Selected')], max_length=100, null=True),
        ),
    ]
