# Generated by Django 4.1.5 on 2023-06-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_candidateuser_skills_alter_application_job_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateuser',
            name='qualification',
            field=models.CharField(choices=[('High School', 'High School'), ('Higher Secondary', 'Higher Secondary'), ('DIPLOMA', 'DIPLOMA'), ('Graduation', 'Graduation'), ('Post Graduation', 'Post Graduation'), ('PhD', 'PhD'), ('other', 'other')], max_length=20, null=True),
        ),
    ]
