# Generated by Django 4.1.5 on 2023-06-14 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_education_add_skill_add_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_skill',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.candidateuser'),
        ),
    ]
