# Generated by Django 4.1.5 on 2023-06-14 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_add_skill_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_skill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.candidateuser'),
        ),
    ]
